jinja2_transforms:
  - name: "dnszone"
    description: "Template to generate terraform configuration for Topology"
    query: "dnszone"
    template_path: "infrahub/templates/dnszone.j2"

queries:
  - name: dnszone
    file_path: "infrahub/templates/dnszone.gql"

artifact_definitions:
  - name: "DNS Zone of Topology"
    artifact_name: "main.tf"
    parameters:
      topology: "name__value"
    content_type: "text/plain"
    targets: "all_topologies"
    transformation: "dnszone"
